# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::rpymat, any::reticulate
          needs: check

      - name: Get conda path
        id: get-conda-path
        run: |
          path <- rpymat:::install_root()
          cat(sprintf("path=%s\n", path), file = Sys.getenv("GITHUB_OUTPUT"))
        shell: Rscript {0}

      - name: Get conda cache key
        id: get-conda-cache-key
        run: |
          v <- tryCatch({
            if( dir.exists(rpymat::env_path()) ) {
              rpymat::ensure_rpymat(verbose = FALSE)
              ants <- reticulate::import("ants")
              ants$`__version__`
            } else {
              1
            }
          }, error = function(e){ 1 })
          # echo "{name}={value}" >> $GITHUB_STATE
          # cat("::set-output name=key::", v, sep = "")
          s <- sprintf("key=%s\n", v)
          cat(s, file = Sys.getenv("GITHUB_STATE"))
          message(s)
        shell: Rscript {0}

      - name: Restore ANTsPy
        id: restore-conda-cache
        if: steps.state.key != '1'
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.get-conda-path.outputs.path }}
          key: ${{ runner.os }}-conda-${{ steps.state.key }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Install ANTsPy
        if: steps.restore-conda-cache.outputs.cache-hit != 'true' || steps.state.key == '1'
        run: |
          python_ver <- "auto"
          verbose <- TRUE
          # Install conda and create a conda environment
          if(!dir.exists(rpymat::env_path())) {
            rpymat::configure_conda(python_ver = python_ver, force = TRUE)
          }
          rpymat::ensure_rpymat(verbose = verbose)
          installed_pkgs_tbl <- rpymat::list_pkgs()

          # install necessary libraries
          pkgs <- c("h5py", "numpy", "scipy", "pandas", "cython")
          if(!all(pkgs %in% installed_pkgs_tbl$package)) {
            rpymat::add_packages(pkgs)
          }

          # install antspyx family
          if(!"antspyx" %in% installed_pkgs_tbl$package) {
            rpymat::add_packages(packages = "antspyx", pip = TRUE)
          }

          rpymat::ensure_rpymat(verbose = FALSE)
          ants <- reticulate::import("ants")
          v <- ants$`__version__`
          s <- sprintf("key=%s\n", v)
          cat(s, file = Sys.getenv("GITHUB_STATE"))
          message(s)
        shell: Rscript {0}

      - name: Cache ANTsPy
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.get-conda-path.outputs.path }}
          key: ${{ runner.os }}-conda-${{ steps.state.key }}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
